name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: 28.2.13676358

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        yes | sdkmanager "ndk;${ANDROID_NDK_VERSION}"
        echo "NDK_HOME=$ANDROID_HOME/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

    - name: Accept Licenses
      run: yes | sdkmanager --licenses

    - name: Build Debug APK
      run: |
        cd V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod +x gradlew
        ./gradlew clean assembleDebug --no-daemon --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: debug-apk
        path: V2rayNG/app/build/outputs/apk/debug/*.apk
